In [1]:
import pandas as pd
import scanpy as sc

In [2]:
%%time
f0   = '/u/home/f/f7xiesnm/project-zipursky/v1-bb/v1/data/allen_yao23/cell_metadata_with_cluster_annotation_l23_vis_ptlp.csv'
f1   = '/u/home/f/f7xiesnm/project-zipursky/v1-bb/v1/data/allen_yao23/WMB-10Xv3-Isocortex-1-raw.h5ad'
f2   = '/u/home/f/f7xiesnm/project-zipursky/v1-bb/v1/data/allen_yao23/WMB-10Xv3-Isocortex-2-raw.h5ad'
fout = '/u/home/f/f7xiesnm/project-zipursky/v1-bb/v1/data/allen_yao23/WMB-10Xv3-VIS-raw.h5ad'

CPU times: user 6 µs, sys: 2 µs, total: 8 µs
Wall time: 14.8 µs

In [3]:
meta = pd.read_csv(f0)
meta

,Unnamed: 0,cell_label,cell_barcode,barcoded_cell_sample_label,library_label,feature_matrix_label,entity,brain_section_label,library_method,region_of_interest_acronym,...,subclass_color,supertype_color,cluster_color,region_of_interest_order,region_of_interest_color,donor_name,external_donor_name,cycle,assay,sex
0,29781,GCACATAGTTTACGAC-447_B06,GCACATAGTTTACGAC,447_B06,L8TX_201204_01_A02,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#5C6899,#1F6624,6,#26AEFF,554815,554815,Light,10Xv3,F
1,29782,AGACAGGTCTGCGATA-447_B06,AGACAGGTCTGCGATA,447_B06,L8TX_201204_01_A02,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#5C6899,#1F6624,6,#26AEFF,554815,554815,Light,10Xv3,F
2,29783,CTAGACATCGATGCAT-447_B06,CTAGACATCGATGCAT,447_B06,L8TX_201204_01_A02,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#5C6899,#43992E,6,#26AEFF,554815,554815,Light,10Xv3,F
3,29784,GGGCCATAGGCACTCC-447_B06,GGGCCATAGGCACTCC,447_B06,L8TX_201204_01_A02,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#5C6899,#43992E,6,#26AEFF,554815,554815,Light,10Xv3,F
4,29785,GCCTGTTTCTCAGTCC-447_B06,GCCTGTTTCTCAGTCC,447_B06,L8TX_201204_01_A02,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#5C6899,#43992E,6,#26AEFF,554815,554815,Light,10Xv3,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,37972,TGTACAGGTGTGGTCC-444_B04,TGTACAGGTGTGGTCC,444_B04,L8TX_201204_01_E01,WMB-10Xv3-Isocortex-2,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#CC7A8F,#AA7ACC,6,#26AEFF,553680,553680,Dark,10Xv3,M
3796,37973,TGTGCGGAGCAGCGAT-444_B04,TGTGCGGAGCAGCGAT,444_B04,L8TX_201204_01_E01,WMB-10Xv3-Isocortex-2,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#CC7A8F,#AA7ACC,6,#26AEFF,553680,553680,Dark,10Xv3,M
3797,37974,TGTTCATAGATGACCG-444_B04,TGTTCATAGATGACCG,444_B04,L8TX_201204_01_E01,WMB-10Xv3-Isocortex-2,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#CC7A8F,#AA7ACC,6,#26AEFF,553680,553680,Dark,10Xv3,M
3798,37975,TTAGGGTGTGGAACAC-444_B04,TTAGGGTGTGGAACAC,444_B04,L8TX_201204_01_E01,WMB-10Xv3-Isocortex-2,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#CC7A8F,#AA7ACC,6,#26AEFF,553680,553680,Dark,10Xv3,M
3799,37976,TTGTTCAAGATCCGAG-444_B04,TTGTTCAAGATCCGAG,444_B04,L8TX_201204_01_E01,WMB-10Xv3-Isocortex-2,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#CC7A8F,#AA7ACC,6,#26AEFF,553680,553680,Dark,10Xv3,M

In [4]:
%%time
adata1 = sc.read(f1)
cells = meta[meta['feature_matrix_label']=='WMB-10Xv3-Isocortex-1']['cell_label'].values
adatasub1 = adata1[cells]
adatasub1

CPU times: user 4.73 s, sys: 15.9 s, total: 20.7 s
Wall time: 1min 42s

View of AnnData object with n_obs × n_vars = 3140 × 32285
    obs: 'cell_barcode', 'library_label', 'anatomical_division_label'
    var: 'gene_symbol'

In [5]:
%%time
adata2 = sc.read(f2)
cells = meta[meta['feature_matrix_label']=='WMB-10Xv3-Isocortex-2']['cell_label'].values
adatasub2 = adata2[cells]
adatasub2

CPU times: user 3.12 s, sys: 11 s, total: 14.1 s
Wall time: 1min 11s

View of AnnData object with n_obs × n_vars = 660 × 32285
    obs: 'cell_barcode', 'library_label', 'anatomical_division_label'
    var: 'gene_symbol'

# merge

In [6]:
adata_merged = sc.concat([adatasub1, adatasub2])
adata_merged

AnnData object with n_obs × n_vars = 3800 × 32285
    obs: 'cell_barcode', 'library_label', 'anatomical_division_label'

In [8]:
adata_merged.obs

,cell_barcode,library_label,anatomical_division_label
cell_label,,,
GCACATAGTTTACGAC-447_B06,GCACATAGTTTACGAC,L8TX_201204_01_A02,Isocortex
AGACAGGTCTGCGATA-447_B06,AGACAGGTCTGCGATA,L8TX_201204_01_A02,Isocortex
CTAGACATCGATGCAT-447_B06,CTAGACATCGATGCAT,L8TX_201204_01_A02,Isocortex
GGGCCATAGGCACTCC-447_B06,GGGCCATAGGCACTCC,L8TX_201204_01_A02,Isocortex
GCCTGTTTCTCAGTCC-447_B06,GCCTGTTTCTCAGTCC,L8TX_201204_01_A02,Isocortex
...,...,...,...
TGTACAGGTGTGGTCC-444_B04,TGTACAGGTGTGGTCC,L8TX_201204_01_E01,Isocortex
TGTGCGGAGCAGCGAT-444_B04,TGTGCGGAGCAGCGAT,L8TX_201204_01_E01,Isocortex
TGTTCATAGATGACCG-444_B04,TGTTCATAGATGACCG,L8TX_201204_01_E01,Isocortex
TTAGGGTGTGGAACAC-444_B04,TTAGGGTGTGGAACAC,L8TX_201204_01_E01,Isocortex
TTGTTCAAGATCCGAG-444_B04,TTGTTCAAGATCCGAG,L8TX_201204_01_E01,Isocortex

In [9]:
meta

,Unnamed: 0,cell_label,cell_barcode,barcoded_cell_sample_label,library_label,feature_matrix_label,entity,brain_section_label,library_method,region_of_interest_acronym,...,subclass_color,supertype_color,cluster_color,region_of_interest_order,region_of_interest_color,donor_name,external_donor_name,cycle,assay,sex
0,29781,GCACATAGTTTACGAC-447_B06,GCACATAGTTTACGAC,447_B06,L8TX_201204_01_A02,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#5C6899,#1F6624,6,#26AEFF,554815,554815,Light,10Xv3,F
1,29782,AGACAGGTCTGCGATA-447_B06,AGACAGGTCTGCGATA,447_B06,L8TX_201204_01_A02,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#5C6899,#1F6624,6,#26AEFF,554815,554815,Light,10Xv3,F
2,29783,CTAGACATCGATGCAT-447_B06,CTAGACATCGATGCAT,447_B06,L8TX_201204_01_A02,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#5C6899,#43992E,6,#26AEFF,554815,554815,Light,10Xv3,F
3,29784,GGGCCATAGGCACTCC-447_B06,GGGCCATAGGCACTCC,447_B06,L8TX_201204_01_A02,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#5C6899,#43992E,6,#26AEFF,554815,554815,Light,10Xv3,F
4,29785,GCCTGTTTCTCAGTCC-447_B06,GCCTGTTTCTCAGTCC,447_B06,L8TX_201204_01_A02,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#5C6899,#43992E,6,#26AEFF,554815,554815,Light,10Xv3,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,37972,TGTACAGGTGTGGTCC-444_B04,TGTACAGGTGTGGTCC,444_B04,L8TX_201204_01_E01,WMB-10Xv3-Isocortex-2,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#CC7A8F,#AA7ACC,6,#26AEFF,553680,553680,Dark,10Xv3,M
3796,37973,TGTGCGGAGCAGCGAT-444_B04,TGTGCGGAGCAGCGAT,444_B04,L8TX_201204_01_E01,WMB-10Xv3-Isocortex-2,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#CC7A8F,#AA7ACC,6,#26AEFF,553680,553680,Dark,10Xv3,M
3797,37974,TGTTCATAGATGACCG-444_B04,TGTTCATAGATGACCG,444_B04,L8TX_201204_01_E01,WMB-10Xv3-Isocortex-2,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#CC7A8F,#AA7ACC,6,#26AEFF,553680,553680,Dark,10Xv3,M
3798,37975,TTAGGGTGTGGAACAC-444_B04,TTAGGGTGTGGAACAC,444_B04,L8TX_201204_01_E01,WMB-10Xv3-Isocortex-2,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#CC7A8F,#AA7ACC,6,#26AEFF,553680,553680,Dark,10Xv3,M
3799,37976,TTGTTCAAGATCCGAG-444_B04,TTGTTCAAGATCCGAG,444_B04,L8TX_201204_01_E01,WMB-10Xv3-Isocortex-2,cell,NaN,10Xv3,VIS-PTLp,...,#E9530F,#CC7A8F,#AA7ACC,6,#26AEFF,553680,553680,Dark,10Xv3,M

# out

In [10]:
adata_merged.write(fout)